### ISSUE TITLE
'TotalItems must be greater than 0'

### ISSUE THREAD

**Issue by gozanohesron** [SitholeWB/Pagination.EntityFrameworkCore.Extensions#4]
I am getting this error 'TotalItems must be greater than 0'. It must be because my expected records is 0. However, since I am passing an Iqueryable item. There is no way for me to know that it is 0 zero records.

I am using it like this

`await documents.AsPaginationAsync(prop.Page, prop.Size, prop.SearchExpression, sortColumn: prop.SortColumn, orderByDescending: prop.SortDirection == "desc")`

**Comment by SitholeWB** [comment]
Prop.Page must not be zero, page counting start from 1 but not zero. Don't think of it as an array.

Please let me know if you continue to experience this issue.

**Comment by gozanohesron** [comment]
Page is 1 and not 0. The issue is that the result set based on my filter (prop.SearchExpression) is 0. So if I don't checked it first, then that exception will throw. However, it defeats the purpose of using the extension AsPaginationAsync if I checked before calling it. It should be able to handle such scenario where you just called AsPaginationAsync and you don't know if it will result to 0 records. Something like this:

`var startIndex = (page - 1) * limit;
        var endIndex = page * limit;

        TotalItems = totalItems;
        CurrentPage = page;

        if (totalItems > 0)
        {
            Results = results ?? Enumerable.Empty<T>();
            if (applyPageAndLimitToResults)
            {
                Results = Results.Skip(startIndex).Take(limit);
            }
            if (startIndex > 0)
            {
                PreviousPage = page - 1;
            }
            if (endIndex < totalItems)
            {
                NextPage = page + 1;
            }

            TotalPages = (int)Math.Ceiling((decimal)totalItems / (decimal)limit);
        }
        else
        {
            Results = Enumerable.Empty<T>();
            PreviousPage = 0;
            NextPage = 0;
            TotalPages = 0;
        }  `

**Comment by SitholeWB** [comment]
I have updated this extension with the latest version [2.3.3](https://www.nuget.org/packages/Pagination.EntityFrameworkCore.Extensions/2.3.3) that allows zero TotalItems, please let me know if I missed something. 
I never thought of scenario of zero TotalItems before, thanks for raising it.
